// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {

    /*ext.kotlin_version = "1.9.25"
    ext.kotlin_coroutines_version = "1.9.0"*/

    apply from: "common_support.gradle"

    ext {
        // compose_version = '1.5.15'
        kcomponent_isMergeOutputFile = true
    }

    ext.component_group_id = "com.xiaojinzi"
    ext.component_asm_util_class_output_path = "./Temp/ASMUtil.class"
    ext.component_asm_disable = false
    // 注解生成器生成的文件 json 信息都
    ext.component_router_doc_folder = "./Doc"
    ext.component_router_doc_enable = false

    repositories {
        google()
        maven {
            url './RepoKComponent'
        }
        maven { url 'https://jitpack.io' }
        jcenter()
    }
    dependencies {
        classpath libs.gradle
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${libs.versions.kotlin.asProvider().get()}"
        classpath "com.xiaojinzi.kcomponent:kcomponent-plugin:${libs.versions.component.asProvider().get()}"
    }

}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.ksp) apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
