plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
    id 'maven-publish'
    id 'org.gradle.kotlin.kotlin-dsl' version '4.5.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(JavaVersion.VERSION_17.toString()))
    }
}

group = 'com.xiaojinzi.kcomponent'
archivesBaseName = 'kcomponent-plugin'
version = libs.versions.component.plugin.upload.get()

// 配置模块的 freeCompilerArgs 参数
/*tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
                "-Xjvm-default=all",
        ]
    }
}*/

/*kotlin {
    jvmToolchain(JavaVersion.VERSION_17)
}*/

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation libs.asm.commons
    implementation libs.asm.util
    implementation libs.gradle
    implementation libs.gson
    implementation libs.grip
    implementation libs.javassist
}

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = archivesBaseName
            version = version
            from components.java
        }
    }
    repositories {
        maven {
            url = "$rootDir/RepoKComponent"
        }
    }
}
