{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "component-plugin-1.0.0-alpha1.jar",
          "url": "component-plugin-1.0.0-alpha1.jar",
          "size": 23504,
          "sha512": "f0d54598e98a802d6260b5f149fa85aae43cd5b306088d7cf06b542720352a904c070d3bf9ddae470a07a12a185b4b4feca75daed9959300811e69bfc27b144a",
          "sha256": "d91abfdfa6bf8b6a45b3cbe8e9d0dd23fa0c536e2f6f359f1f8b86cb6bc80e3a",
          "sha1": "cf72660fc4b8f55cac9261debfbd67a217a494c7",
          "md5": "1ab9432c1f0710ea67235fd75182fb7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-1.0.0-alpha1.jar",
          "url": "component-plugin-1.0.0-alpha1.jar",
          "size": 23504,
          "sha512": "f0d54598e98a802d6260b5f149fa85aae43cd5b306088d7cf06b542720352a904c070d3bf9ddae470a07a12a185b4b4feca75daed9959300811e69bfc27b144a",
          "sha256": "d91abfdfa6bf8b6a45b3cbe8e9d0dd23fa0c536e2f6f359f1f8b86cb6bc80e3a",
          "sha1": "cf72660fc4b8f55cac9261debfbd67a217a494c7",
          "md5": "1ab9432c1f0710ea67235fd75182fb7c"
        }
      ]
    }
  ]
}
