{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "2.0.0-beta12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "component-plugin-2.0.0-beta12.jar",
          "url": "component-plugin-2.0.0-beta12.jar",
          "size": 25196,
          "sha512": "5075f986adf8f4c835625f16651e34b3669ca4dab9d6cdb6d4cd0bdd078558d8f8e655a77c0ae29acabbb428f4e5179d46b6e8bb183f9627a760ae2b0ae2c338",
          "sha256": "6ea5fb9339205c939d64567e5e210c5ed681666cc09737a7ccfb298fcee80a5a",
          "sha1": "96f811a358a7ad158173ecfc0d46be9984f2bd67",
          "md5": "383774773419b12010e41f5b6b913cb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-2.0.0-beta12.jar",
          "url": "component-plugin-2.0.0-beta12.jar",
          "size": 25196,
          "sha512": "5075f986adf8f4c835625f16651e34b3669ca4dab9d6cdb6d4cd0bdd078558d8f8e655a77c0ae29acabbb428f4e5179d46b6e8bb183f9627a760ae2b0ae2c338",
          "sha256": "6ea5fb9339205c939d64567e5e210c5ed681666cc09737a7ccfb298fcee80a5a",
          "sha1": "96f811a358a7ad158173ecfc0d46be9984f2bd67",
          "md5": "383774773419b12010e41f5b6b913cb8"
        }
      ]
    }
  ]
}
