{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "kcomponent-plugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 24020,
          "sha512": "f9cad299fe109da2dc2d074b264427d64c8bbb7eee72781af205a797f4a1522eae591d06d16b06229227b67f2920d0c4f9ba3d7b9b02751205f69c19fb12d21a",
          "sha256": "f036ead61909c5d88c9460380f2001d61a6a54383346b87a2be7c0948bb56a59",
          "sha1": "54ff0fd35eac3dcf15679280c6a11fc53a9a3699",
          "md5": "22773627034aaf39342e8ca3d01fc31d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 24020,
          "sha512": "f9cad299fe109da2dc2d074b264427d64c8bbb7eee72781af205a797f4a1522eae591d06d16b06229227b67f2920d0c4f9ba3d7b9b02751205f69c19fb12d21a",
          "sha256": "f036ead61909c5d88c9460380f2001d61a6a54383346b87a2be7c0948bb56a59",
          "sha1": "54ff0fd35eac3dcf15679280c6a11fc53a9a3699",
          "md5": "22773627034aaf39342e8ca3d01fc31d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1-sources.jar",
          "url": "kcomponent-plugin-1.0.0-beta1-sources.jar",
          "size": 4740,
          "sha512": "ef876e734c3f2e07e513927e1cbbb87db957ab931783df6d6186678a1dfeed80a066a96b6f28f7a8c1549e355fd16d60d0b1a606e779b7728ed8fd66e23757de",
          "sha256": "8f02d8e451f88856125798ab73a640a858d02aa299e69ea4c15b0b221ffe1ca3",
          "sha1": "09ea47bc6224c32568d6c55a6cd6915672ba6717",
          "md5": "0f8ee2d2c28fbab5a043abe2767912d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1-javadoc.jar",
          "url": "kcomponent-plugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "8fd928ddeedb85d12fb134200c368a97ea32b786e8ee9392bbead205b32929ea2854172d5f57022d5750be489e306a7c3a71c8709bf87310583b82eea3bebe2a",
          "sha256": "d9ec31553f797e1e358310b4b66d2ad234a94c06128ea3d67f127aafeab1c2a0",
          "sha1": "599c895612a347f4e3997af5880d0cec6bf4eafa",
          "md5": "1584a291c39494416acae8a6abc3d16f"
        }
      ]
    }
  ]
}
