{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "kcomponent-plugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 14687,
          "sha512": "caf80af45fc98a6dc75c52fd20e7c052dd631dba1f21df4ea4dd114f5108069c49735a7a59e87c09669e18087e5936a7ffc25a0f992c87ed89077e5e07d2b040",
          "sha256": "1d316adae497037ec5515b124f1f3929f946f7596ea49eb425707744717f9a9b",
          "sha1": "7e731e4e694b4ec00dd769d2089cc4088d4fd2b1",
          "md5": "04c544736123b489a2136d91b2dffdf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 14687,
          "sha512": "caf80af45fc98a6dc75c52fd20e7c052dd631dba1f21df4ea4dd114f5108069c49735a7a59e87c09669e18087e5936a7ffc25a0f992c87ed89077e5e07d2b040",
          "sha256": "1d316adae497037ec5515b124f1f3929f946f7596ea49eb425707744717f9a9b",
          "sha1": "7e731e4e694b4ec00dd769d2089cc4088d4fd2b1",
          "md5": "04c544736123b489a2136d91b2dffdf3"
        }
      ]
    }
  ]
}
