{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "kcomponent-plugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 24845,
          "sha512": "8dea6d79a363eba53910a813ebe13514fe935c64372692e12abaaacc4dfedb01cb1a50b6a85c5636fe773b67a28f5f33484809161a285507621faf441fa3815e",
          "sha256": "1c83752c20892570b385cd5c5203fd76a6ef9f5e44d9b692976ee1673d2bd9cb",
          "sha1": "141b28492dd97b6ded5c70bd9d3f986179beefc0",
          "md5": "4fe42422a5141b01a9522696816263ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        },
        {
          "group": "com.github.gundy",
          "module": "semver4j",
          "version": {
            "requires": "0.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1.jar",
          "url": "kcomponent-plugin-1.0.0-beta1.jar",
          "size": 24845,
          "sha512": "8dea6d79a363eba53910a813ebe13514fe935c64372692e12abaaacc4dfedb01cb1a50b6a85c5636fe773b67a28f5f33484809161a285507621faf441fa3815e",
          "sha256": "1c83752c20892570b385cd5c5203fd76a6ef9f5e44d9b692976ee1673d2bd9cb",
          "sha1": "141b28492dd97b6ded5c70bd9d3f986179beefc0",
          "md5": "4fe42422a5141b01a9522696816263ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1-sources.jar",
          "url": "kcomponent-plugin-1.0.0-beta1-sources.jar",
          "size": 4676,
          "sha512": "be192b14771523736e45d3df75b247d0e68450af4c2b569b8ed53649c7bdeeb412cdb8f2def1c989c7364fbe51013a917b599b3ba1b749342a494986931d134a",
          "sha256": "a0dcd3e4f60c727a2b98f34ec2f7a4e117215a9ad513a60fe893d9758a96c824",
          "sha1": "bedfce2a9ffcfca0569cdf6261b19a2250f13a6c",
          "md5": "49aa7164fc4f180944549993ac31442e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin-1.0.0-beta1-javadoc.jar",
          "url": "kcomponent-plugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "4e8d4cfdbecc7707265bbc9b7b136901c91a757d45d76529e1f4e0cc78781c7abeecad703cd5077c988ef8638b87967c510a01cf9aac87f0463332ec7580f52e",
          "sha256": "d415fa99286ea053153fbd1ab5ba3503a431dc1634757b4ca66740167e87bb19",
          "sha1": "054ca39baafd48c98f17563bf2a695cc3e635858",
          "md5": "7eb0feb70f88fee85dfed435dcf6d5ac"
        }
      ]
    }
  ]
}
