{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "ComponentPlugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1.jar",
          "url": "ComponentPlugin-1.0.0-beta1.jar",
          "size": 20158,
          "sha512": "93a0f4461d4d0998e25b30c98e861d70006b2bdd3aaf277f1ad704c654ac20a26a43c6fb27b6049aaf104e7d6f3c8478419de22c9c971ab1445c4b6802560a10",
          "sha256": "46bc6cfa3ac36e030e048c747087a7f7cdd25f77180c2ddcc18fd16ef6522649",
          "sha1": "c9ac00ef3bba9245421a0e42618bd74eb58d613b",
          "md5": "bdaa53ec10aecf74325c70ae517d1a99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1.jar",
          "url": "ComponentPlugin-1.0.0-beta1.jar",
          "size": 20158,
          "sha512": "93a0f4461d4d0998e25b30c98e861d70006b2bdd3aaf277f1ad704c654ac20a26a43c6fb27b6049aaf104e7d6f3c8478419de22c9c971ab1445c4b6802560a10",
          "sha256": "46bc6cfa3ac36e030e048c747087a7f7cdd25f77180c2ddcc18fd16ef6522649",
          "sha1": "c9ac00ef3bba9245421a0e42618bd74eb58d613b",
          "md5": "bdaa53ec10aecf74325c70ae517d1a99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1-sources.jar",
          "url": "ComponentPlugin-1.0.0-beta1-sources.jar",
          "size": 4030,
          "sha512": "9e38aafd6f4c6d9ee730095d7a302275e64aa5e4ab8ae6f37e5330ec7620e9f0b037f2c597080f51727928f3753766a044694fd6582f659215f3a5bf0fa77b23",
          "sha256": "241cea77d5bd37bb5d6e9ce3f98e59f7e561563ad58e42cdc1adf133f6a2cb0b",
          "sha1": "a20b3dd341bca12658dee6ae00166e177e6b8910",
          "md5": "f8ccec61d7f696abfdc4439d0ac2c9c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1-javadoc.jar",
          "url": "ComponentPlugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "a6f26989ec5249252f9b522c2f8e82c10396455a0d63e05ce82cf841ac1af2589639b8b2509d2b96cde6afdb66846b62aaf4911345fec3fe8e9395cf9e385d94",
          "sha256": "141c39788c633ba8ce287df0f00e163ea2a7f4adc89c7f76b8c07391a47cc53a",
          "sha1": "288480818dd835abe04d2e88b2923ba85493d100",
          "md5": "89828e50e3ef2f9b9297fcf04e9a18f9"
        }
      ]
    }
  ]
}
