{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "ComponentPlugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1.jar",
          "url": "ComponentPlugin-1.0.0-beta1.jar",
          "size": 25140,
          "sha512": "014e8a4093d41b24fa8b4215c49b7c40dd31d5527c1a16699e7237f941c2c54c74d51a5cdfdc855da8660cf0e9298126f8b00d90b085e62853e3179f51b0928b",
          "sha256": "7fb76d97a3b3098dd35bd71e52c1feecffabbde8fe8dc3eea79f15d8a86ae6ed",
          "sha1": "2e0b8eb31df61dd8a7cc64a2624b7703dd8d5dbe",
          "md5": "0a403300615426c1e96c009f46e91612"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        },
        {
          "group": "com.github.gundy",
          "module": "semver4j",
          "version": {
            "requires": "0.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1.jar",
          "url": "ComponentPlugin-1.0.0-beta1.jar",
          "size": 25140,
          "sha512": "014e8a4093d41b24fa8b4215c49b7c40dd31d5527c1a16699e7237f941c2c54c74d51a5cdfdc855da8660cf0e9298126f8b00d90b085e62853e3179f51b0928b",
          "sha256": "7fb76d97a3b3098dd35bd71e52c1feecffabbde8fe8dc3eea79f15d8a86ae6ed",
          "sha1": "2e0b8eb31df61dd8a7cc64a2624b7703dd8d5dbe",
          "md5": "0a403300615426c1e96c009f46e91612"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1-sources.jar",
          "url": "ComponentPlugin-1.0.0-beta1-sources.jar",
          "size": 4737,
          "sha512": "c73ce8712454cc44a03bcae3b32e03075c00eb68d48233d94698ef003696341261e44b804c38cfbb07a939f67832b46c6b8ce0ce78f8c9c5206c4f4e4c7d14a5",
          "sha256": "57c3b026f2d966c90beef8149456ddd31fa7a3b04d6707a47822f0b194890580",
          "sha1": "cec3d84849d06d2865beff05e42979ecb500210a",
          "md5": "ca23452e6f53cfc6849ea7303dccd6e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1-javadoc.jar",
          "url": "ComponentPlugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "5f57869813269f17ab4855a5cd7ab8ac3d9fe14115b194b6b9e12f1d4df25a7a908092e618ea14a705f4b1a84c07ca9da1bc2f19f566f466566654fb38010eac",
          "sha256": "a45154de5bb77dfaa36fa0619185cb43fed0a8385d044d4902c32eb91c505fd3",
          "sha1": "0f57cf9512cd265880e4fb44ed837f3a2e12e63d",
          "md5": "4fb4a50364d5942703d58fed17cc5840"
        }
      ]
    }
  ]
}
