{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "ComponentPlugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1.jar",
          "url": "ComponentPlugin-1.0.0-beta1.jar",
          "size": 21748,
          "sha512": "cad7d8e1be7c5948c72fcd2cb8a800e424381b6c6e6e5a92c3281bbdf10ed5bf3044df27fbac85a79003bb21cca7c6d47d8fa8f7917cf1bf5230c3147c6b1300",
          "sha256": "921c1bde7434a9a7a43a6118d2f16e4ac5faeb1daa7aa2c81e42e2710bf1b5f6",
          "sha1": "5f1e91883bcd7f0d777a538b085f6bcaf3b8e489",
          "md5": "194f3a0ba7d9a5f6541f5d5c83590e9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1.jar",
          "url": "ComponentPlugin-1.0.0-beta1.jar",
          "size": 21748,
          "sha512": "cad7d8e1be7c5948c72fcd2cb8a800e424381b6c6e6e5a92c3281bbdf10ed5bf3044df27fbac85a79003bb21cca7c6d47d8fa8f7917cf1bf5230c3147c6b1300",
          "sha256": "921c1bde7434a9a7a43a6118d2f16e4ac5faeb1daa7aa2c81e42e2710bf1b5f6",
          "sha1": "5f1e91883bcd7f0d777a538b085f6bcaf3b8e489",
          "md5": "194f3a0ba7d9a5f6541f5d5c83590e9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1-sources.jar",
          "url": "ComponentPlugin-1.0.0-beta1-sources.jar",
          "size": 4238,
          "sha512": "6d9691021bcb8791d87fb6ee9262041279bc9ebb3515e0ede23e66084f60a0256064893295eef09ea9c392591667b715ba8bc1674503fd80eeaab483348c0440",
          "sha256": "191b8e272646fb75384a0c6cad1c522d3b2ac4e8d8ffaba2fcc7ee8ab7dab8e0",
          "sha1": "1d09e8491893835b96c8dea1b5ef8881e898fd5d",
          "md5": "48e0b23900a138fc66a12983517e323f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ComponentPlugin-1.0.0-beta1-javadoc.jar",
          "url": "ComponentPlugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "bb27b2b657f5faa8c1617ab323638a781756760b907e66c9b2f50b4ae8bf9dec4bbac749c6e626d747b46924ea69f69ee3992ad449f80f9183f44d2ddf978dee",
          "sha256": "b8a545f952be7ba534bd85e5dab5e11cae4c2d7415f95ccc3d589907109cff6e",
          "sha1": "8fc93a2fa347a9165c2eef6370fa4078dd737917",
          "md5": "a35bbc6d32f43bcad23efe1c9f4213d9"
        }
      ]
    }
  ]
}
