{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.kcomponent",
    "module": "kcomponent-plugin2",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kcomponent-plugin2-1.0.0-beta1.jar",
          "url": "kcomponent-plugin2-1.0.0-beta1.jar",
          "size": 15859,
          "sha512": "ae1901e366323bd8b4c96db2388b94b3fb71c6eb3c56f878738c69a22fd29471d8a42f06549acaad3733d7e1da9bca90a96a5690f7919440b3fea66bcd2fb59e",
          "sha256": "b05bf8a5ded6f3815d1d76838faf41fa94dc24e3c38f7ef7b0095c10a030270e",
          "sha1": "fb683be75e4e97d4493d5fb049e9faa6820bf8ac",
          "md5": "51debb9c91958efff99973d0ddefac92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kcomponent-plugin2-1.0.0-beta1.jar",
          "url": "kcomponent-plugin2-1.0.0-beta1.jar",
          "size": 15859,
          "sha512": "ae1901e366323bd8b4c96db2388b94b3fb71c6eb3c56f878738c69a22fd29471d8a42f06549acaad3733d7e1da9bca90a96a5690f7919440b3fea66bcd2fb59e",
          "sha256": "b05bf8a5ded6f3815d1d76838faf41fa94dc24e3c38f7ef7b0095c10a030270e",
          "sha1": "fb683be75e4e97d4493d5fb049e9faa6820bf8ac",
          "md5": "51debb9c91958efff99973d0ddefac92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin2-1.0.0-beta1-sources.jar",
          "url": "kcomponent-plugin2-1.0.0-beta1-sources.jar",
          "size": 3114,
          "sha512": "70d7a196494539fa65fd0b376ce76f7696880fdafbe5662e3bc1609f52702af5232402a62ab52f9e1928d7bd131c9d44f8f6968093f1a66ec8b1f44b69dbf380",
          "sha256": "b8df23be98a9d804908caeac8dba0e344288914a16ff5c5ef5c274a1cb7fca59",
          "sha1": "0106d533d89f1771411c721a6188e3b71dac403d",
          "md5": "772830cc1e9eecdf7c65b8bd23d9daad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kcomponent-plugin2-1.0.0-beta1-javadoc.jar",
          "url": "kcomponent-plugin2-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "3b3530258553ec4c4fcf6e779f1911bfb8d1887d54f8fa52e8a30ccf7c2320f7adea7096ba103927a904a6a9043b04592cd261ccf0cee524a38f27f2497a22b6",
          "sha256": "65326589e39aeeb3b93f39ed43039d024299da0bec2c9382e8b62910450cd12e",
          "sha1": "c4b8f82576eac8a9d03136df342e716e07cff179",
          "md5": "196d953007e170bda697a21e0d9b2c27"
        }
      ]
    }
  ]
}
